version: '3.7'

services:
  rmc_nginx:
    container_name: rmc_nginx
    build:
      context: ./nginx
    user: ${DOCKER_USER}
    ports:
      - "80:80"
    volumes:
      - ../../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
    depends_on:
      - rmc_php

  rmc_php:
    container_name: rmc_php
    build:
      context: ./php
    user: ${DOCKER_USER}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ../../:/var/www

  rmc_mysql:
    container_name: rmc_mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - rmc_mysql:/var/lib/mysql

volumes:
  rmc_mysql:
